import { stateAuthoritativeFacade } from "../core/index.js";

const {
  claimTask,
  claimTaskLifecycle,
  blockTask,
  blockTaskLifecycle,
  markTaskReadyForReview,
  markTaskReadyForReviewLifecycle,
  completeTask,
  completeTaskLifecycle,
  approveTask,
  approveTaskLifecycle,
  rejectTask,
  rejectTaskLifecycle,
  releaseTask,
  releaseTaskLifecycle,
  activateSwarm,
  blockSwarm,
  completeSwarm,
  cancelSwarm,
} = stateAuthoritativeFacade;

export {
  claimTask,
  claimTaskLifecycle,
  blockTask,
  blockTaskLifecycle,
  markTaskReadyForReview,
  markTaskReadyForReviewLifecycle,
  completeTask,
  completeTaskLifecycle,
  approveTask,
  approveTaskLifecycle,
  rejectTask,
  rejectTaskLifecycle,
  releaseTask,
  releaseTaskLifecycle,
  activateSwarm,
  blockSwarm,
  completeSwarm,
  cancelSwarm,
};
