import { stateAuthoritativeFacade } from "../../../state-runtime-core.js";

const {
  annotateTask,
  annotateTaskMutation,
  addTask,
  addTaskLifecycle,
  addTasks,
  storeMemory,
  storeMemoryMutation,
  initSwarm,
  initSwarmMutation,
  updateTask,
  updateTaskMutation,
  archiveTask,
  archiveTaskMutation,
  restoreTask,
  restoreTaskMutation,
  reopenTask,
  reopenTaskMutation,
  updateSwarm,
  updateSwarmMutation,
  archiveSwarm,
  archiveSwarmMutation,
  restoreSwarm,
  restoreSwarmMutation,
  reopenSwarm,
  reopenSwarmMutation,
  queueSwarmTasks,
  dispatchSwarmLane,
} = stateAuthoritativeFacade;

export {
  annotateTask,
  annotateTaskMutation,
  addTask,
  addTaskLifecycle,
  addTasks,
  storeMemory,
  storeMemoryMutation,
  initSwarm,
  initSwarmMutation,
  updateTask,
  updateTaskMutation,
  archiveTask,
  archiveTaskMutation,
  restoreTask,
  restoreTaskMutation,
  reopenTask,
  reopenTaskMutation,
  updateSwarm,
  updateSwarmMutation,
  archiveSwarm,
  archiveSwarmMutation,
  restoreSwarm,
  restoreSwarmMutation,
  reopenSwarm,
  reopenSwarmMutation,
  queueSwarmTasks,
  dispatchSwarmLane,
};
